# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\"I\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\"\x07\n\x05\x45mpty\" \n\x08TaskList\x12\x14\n\x05tasks\x18\x01 \x03(\x0b\x32\x05.Task\"\x14\n\x06TaskId\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xc0\x01\n\x0bToDoService\x12\x17\n\x07\x41\x64\x64Task\x12\x05.Task\x1a\x05.Task\x12\x19\n\x07GetTask\x12\x07.TaskId\x1a\x05.Task\x12\x1e\n\tListTasks\x12\x06.Empty\x1a\t.TaskList\x12\x1a\n\nUpdateTask\x12\x05.Task\x1a\x05.Task\x12\x1c\n\nDeleteTask\x12\x07.TaskId\x1a\x05.Task\x12#\n\x11MarkTaskCompleted\x12\x07.TaskId\x1a\x05.Taskb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=14
  _globals['_TASK']._serialized_end=87
  _globals['_EMPTY']._serialized_start=89
  _globals['_EMPTY']._serialized_end=96
  _globals['_TASKLIST']._serialized_start=98
  _globals['_TASKLIST']._serialized_end=130
  _globals['_TASKID']._serialized_start=132
  _globals['_TASKID']._serialized_end=152
  _globals['_TODOSERVICE']._serialized_start=155
  _globals['_TODOSERVICE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
